#ifndef __TRASH_H
#define __TRASH_H

#define MKEY_A 0x41
#define MKEY_B 0x42
#define MKEY_C 0x43
#define MKEY_D 0x44
#define MKEY_E 0x45
#define MKEY_F 0x46
#define MKEY_G 0x47
#define MKEY_H 0x48
#define MKEY_I 0x49
#define MKEY_J 0x4A
#define MKEY_K 0x4B
#define MKEY_L 0x4C
#define MKEY_M 0x4D
#define MKEY_N 0x4E
#define MKEY_O 0x4F
#define MKEY_P 0x50
#define MKEY_Q 0x51
#define MKEY_R 0x52
#define MKEY_S 0x53
#define MKEY_T 0x54
#define MKEY_U 0x55
#define MKEY_V 0x56
#define MKEY_W 0x57
#define MKEY_X 0x58
#define MKEY_Y 0x59
#define MKEY_Z 0x5A

PFNGLGENBUFFERSPROC glGenBuffers;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;
PFNGLBINDBUFFERPROC glBindBuffer;
PFNGLBUFFERDATAPROC glBufferData;
PFNGLBINDVERTEXARRAYPROC glBindVertexArray;
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;
PFNGLCREATESHADERPROC glCreateShader;
PFNGLSHADERSOURCEPROC glShaderSource;
PFNGLCOMPILESHADERPROC glCompileShader;
PFNGLCREATEPROGRAMPROC glCreateProgram;
PFNGLATTACHSHADERPROC glAttachShader;
PFNGLLINKPROGRAMPROC glLinkProgram;
PFNGLUSEPROGRAMPROC glUseProgram;
PFNGLGENVERTEXARRAYSPROC glGenVertexArrays;
PFNGLGETATTRIBLOCATIONPROC glGetAttribLocation;
PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray;
PFNGLGETSHADERIVPROC glGetShaderiv;
PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog;
PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation;
PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv;
PFNGLACTIVETEXTUREPROC glActiveTexture;
PFNGLUNIFORM1IPROC glUniform1i;
PFNGLUNIFORM3FPROC glUniform3f;
#endif

